package org.lilbrocodes.constructive.api.v1.anno.builder;

import java.lang.annotation.*;

/**
 * Sets the names for the classes generated by Constructor.
 * By default, the name will be [class name][Builder/Serializer/Deserializer].
 * <br>For example, the default names for a class named 'Person' would be:
 * <ul>
 *  <li>PersonBuilder</li>
 *  <li>PersonSerializer</li>
 *  <li>PersonDeserializer</li>
 * </ul>
 * By default, the package will be the same as of the marked class. If {@link Target#rel()} is disabled,
 * the package must be provided in the format of a full package id, like 'org.lilbrocodes.constructive.builders'.
 * Otherwise, they can be provided in the format of relative package id, like 'builders'- which will equal 'org.lilbrocodes.constructive.builders',
 * if the package of the parked class is 'org.lilbrocodes.constructive'. Including '..' in the package name will escape one package node.
 */
@java.lang.annotation.Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface Target {
    String builder() default "";
    String builderPackage() default "";
    String serializer() default "";
    String serializerPackage() default "";
    String deserializer() default "";
    String deserializerPackage() default "";

    boolean rel() default false;
}
